spring.application.name=vehicle-service

# Detalle de esta configuracion: Obsidian Tartis-Recon-IA.
spring.config.import=optional:file:.env[.properties]

spring.profiles.default=dev

spring.jpa.open-in-view=false

spring.docker.compose.enabled=false

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

springdoc.swagger-ui.url=/openapi.yml
